# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    get_certificates
    get_provisioning_profile
    increment_build_number(xcodeproj: "FitHub.xcodeproj")
    build_app(scheme: "FitHub",
		slack_url: "https://hooks.slack.com/services/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",
		slack_channel: "#iOS-배포")
    upload_to_testflight
  end
end
